def clean_text_to_prompt(text,length):
    # Replace multiple spaces/tabs with a single space
    cleaned_text = ' '.join(text.split()[:length])
    return cleaned_text

# Example usage:
# Assuming you have a large text from an open-source book
input_text = """My first voyage at sea was on March 25th, 1850. I started out as a big fat boy of eight years and eight months to do the cooking on board the schooner Pennsylvania, Captain Tracy Kenney as skipper.
We left home at eight in the morning, loading our bed sacks and bedding onto a team belonging to a man by name of Daniel Higgins, who carried the goods to Suet Creek, West Dennis, Mass. It was a fine morning, and with the crew I trudged along until at twelve we reached the old schooner, which had been hauled up for the winter. The tide was out and she lay on her broad side, looking for all the world like an abandoned old hulk. Nevertheless, I was destined to get the first baptism of old ocean aboard of her, learn some hard lessons, and acquire a love of salt water that would never be lost. The sea has ever been and ever will be a wondrous magnet to many men.
Our bedding and earthly goods were put on board and we proceeded to make things as comfortable as possible. Each one had his little sugar tub with grub enough to last until we reached Boston, where we were going to fit out with salt and provisions for a voyage to the Grand Banks. The stench from bilge water and mustiness, as the vessel had been closed all winter, was something terrible, and the stove and pipe were covered with rust half an inch thick.
The schooner was lying on her port bilge and there was hardly room to stand up, yet late in the afternoon the tide came in and it was more comfortable. The anchors were placed down stream and the vessel was hove off the bank and put down stream alongside a small wharf where our sails and gear were stored in a shed. The men bent sails and rove gear and made ready to start for Boston.
In the meantime I had been cleaning up the cabin, scrubbing the rust from the stove and greasing it. I had no cooking to do, only to make tea and coffee, set each man’s tub by his side, when they all fell to and helped themselves. Our plates, knives and forks were of ancient type, tin plates, iron spoons, and knives and forks which had to be constantly scoured with wood ashes to make them presentable.
Salt water had to be used for dish water, and one can imagine how my dish cloths looked washed with salt water soap. While the grease was on the stove I had the fire going, and the companion was full of smoke. Every few moments some one of the boys would shout down to me, “Hi, cookie, your dish cloths are burning on.”
On the morning of the third day after leaving home, we dropped down the creek into Barnstable Bay and made sail for Boston.
Oh, my, wasn’t I homesick! I was a great mother’s boy, and would have given all I possessed could I have been back with her. It seemed cruel to me then, and has many times since, to think that a boy less than nine years old should have to leave home to help support the family. But such were the economic conditions of the times that all were obliged, when families were as large and as poor as mine was, to contribute to the general support. But I was glad to help out all I could, and the call of the deep blue sea was hard to resist. How often had I listened to tales of foreign lands, of smart skippers, and big ships, and at last my chance had come.
[Pg 6]
My salary was the magnificent sum of forty-five dollars for the season and fifty cents per hundred for every cod fish that I caught. We had a fine run to Boston, and at sundown was alongside the wharf at Chelsea, Mass. There we took on board seventy-five hogsheads of salt to salt the fish we expected to catch. After this was on we pulled the old craft over to Boston and took in our provisions for the trip.
They consisted of barrels of salt pork, beef, a barrel of beans, half a barrel of rice, five barrels of flour and corn meal and a big barrel of molasses to make sweet cake with, as this was a great treat to the fishermen at supper nine days out of ten while on the Grand Banks. We also used the molasses to sweeten our coffee with, as sugar was too costly at that time to feed fishermen.
One afternoon I strode up to Commercial Street with one of the men, who went to a ship chandler’s shop to get his fit out of lines and hooks and other little things he wanted for the trip. I waited for him outside. At that time the bow-sprits of the vessels stuck over into what is now Commercial Street, but which at the present time is all filled in. This was my first trip away from home, and I stood staring with open mouth at the sights. At last I commenced to look for my friend, a man named Long, but he had evidently forgotten me and gone back to the schooner. The rush and roar of the great city confused and frightened me, and I was scared half out of my wits. I had forgotten the name of the schooner, and when about in despair and ready to give up I saw a man from Orleans that I knew, a Captain John Gould, and in pitiful tones I told him I was lost. How he laughed, and pointing over his shoulder he said, “There is your old wash tub, Bub; you ought to pick her out of ten thousand,” and went along, roaring as he went. And years after, when I thought of that old schooner with the Dutch bows, I have laughed, too, though to me at that time she was a great ship.
Back on board, I started to cook my supper for the now hungry crew. It consisted of boiled potatoes, with fat salt pork scraps, biscuits and chocolate. They ate all of my cream of tartar biscuits, and I had to be content with hard bread for my supper. However, I naturally was looking for compliments on those biscuits, but all I got was a sharp growl from the Captain, who asked me if I had washed my hands before I had made them.
We soon had our stores on board, but were detained in Boston for a few days by a heavy storm with northeast gales. It snowed very heavily, and it was the third of April before we at last made sail and sailed down the channel with a light wind blowing from the westward.
When off Boston Light it began to be very rough, with a heavy ground swell, and it was here that I, for the first and only time during my entire sea life, was seasick. And I certainly was sick! I asked the men to throw me overboard I was so miserable, but they only laughed and made fun of me. Some said, “O, Cookie, take a piece of raw pork and tie it to a string, swallow it and haul it up and down; it’s a sure cure.”
Mr. Samuel Sherman, who was mate, now came down and drove away my tormentors. He was very kind to me, and I never forgot it. He got the dinner for me and cleared it away, and as we got further down the bay the water got smoother, and before we anchored inside Billingsgate Island at Orleans I was quite myself again. Early that evening I was home again with my folks, and
[Pg 7]
 I had wonderful tales to tell of Boston and of the things I had seen on the trip. In the old days it was the custom to stay in the home port after fitting out for a trip of fishing and to remain there a few days.
We then went to Provincetown and took on fresh water, which was put in barrels, stored in the fore hold and chocked up with wood, which we used to kindle the fire with. We took on at that time about fifty barrels of water.
We then took our departure for the Grand Banks, steering to eastward for a distance of about nine hundred miles, passing north of Sable Island, and running free most of the way by dead reckoning. When the Captain judged himself near the Banks we often sounded with the lead and line, and on the evening of the seventh day out from Cape Cod we baited up our lines and threw them overboard. As soon as the lead struck bottom they had a bite, and the Captain shouted out, “Let go the anchor; we are right on top of them.” Sure enough, up came a fine pair of cod-fish weighing about ten pounds each. Down came all sail and we played out about a hundred fathom of cable, made it fast around the windlass, put our riding sail up aft to keep her up to the wind and steady her. We set a big lantern on a pole out aft, and then all went below to make up the anchor watch. We divided up the time from 8 p.m. to 5 a.m., which gives each man the same amount of duty. In the locality of the Banks one encounters a great deal of fog, so much so, in fact, that it is impossible to tell whether the next hour will be fine or clear. It is so thick that at times you can barely see the hand in front of the face, and strict orders were given to keep a sharp look out for sailing ships, and especially for steamers. However, in those days sailing ships were in the great majority, and trade from all ports of the States were bound eastward, and many were those we saw on the Banks. So in foggy weather we kept the fog horn going all the time, and the “Old Man” always slept with one eye open.
On the next morning the deck watch was called, as the fish had commenced to bite in good shape, and five men were heaving them as fast as they could haul them in. Each line had a rig for two hooks, and each man tended two lines. In the deck space between each man was a large deck-kid or box, which was made stationary and had a partition on the inside to separate the fish that each man caught. Each gang fished for two hours, and then the watch was changed.
Then they counted out the number of fish that each man had caught and threw them into the main deck-kid or dressing bin, cleaned their fish and prepared them for the salting process which takes place in the hold of the schooner. One man throated, gutted and took out the cod tongues, placed them on the dressing table for the splitter, who took out the back-bones and threw the fish into a tub to wash out the blood. It was the cook’s job to pitch the fish down the hatch-way to the salter in the hold below. The salter was a man well adapted to see that the fish were properly salted and stowed away. And so it goes on, day in and day out, fish for two hours and then change.
The fish usually stop biting as soon as the sun goes down, and after supper is over the Captain opens his log-book and records the tally of each man’s catch that day. At the end of the voyage this shows the standing of each man, and the one who catches the most fish is called “high-liner,” and is considered a valuable man and is much sought after by the owners, who wish to re-ship the
[Pg 8]
 man for another season. It often happens that a man may be a first class sailor but has not acquired the knack of hooking a fish, and for such a poor fellow the chances of his getting on a crack fishing schooner were small.
On our boat Mr. Samuel Sherman was “high-liner” and had held the record for years and was called “second hand,” a position corresponding with that of a mate and next to the Captain in command. The old-time fisherman carried no mate, all authority vesting in the Skipper or Captain. The whole crew were on the same footing, and did practically what they pleased and gave suggestions and advice as freely as they wished. Mr. “Cookie” usually turns out about 2.30 a.m., makes his fire, puts his biscuit in the oven, makes two gallons of coffee, and calls “all hands” at 3.45 for breakfast. The crew tumble out, clothing all on except coat, hat and boots, and how they could eat! And then for the fish again.
On Sunday we did no fishing, had breakfast at 7 a.m., and spent the day in cleaning up and lying around. We used to make about 300 doughnuts for our Sunday morning breakfast, and it was here that my good friend Mr. Sherman came to my rescue and helped me out with the work. He was certainly one true Christian gentleman, a good and kind man. Our Sunday dinner was “salt-horse,” or boiled dinner, with a large steamed apple duff of dried apples, and for supper we always had fried mince-pies. I tell you, we lived high!
Our Captain was a very pious man. He was called by those who knew him well “a summer Christian and a winter devil.” On Sunday morning he always prayed and read a chapter from the Bible and sang his favorite hymns. His favorite songs were, “A Soldier for Jesus” and “Love and Serve the Lord.” I used to snicker, as the Captain had no teeth to speak of, and his voice was very flat and lispy. The name of Lord always sounded like Lard. I often had my ears boxed when the men would say, “Cookie, sing like Captain,” and I would put in, in earnest. Then the Captain would cuff me and say, “You sassy thing, I will report you to your mother when we get home.” They both belonged to the same church, but I had no reason to fear on that score, as my mother was an earnest and devout Christian, always self-sacrificing, and loved by all who knew her, ever ready and willing to help and see good in everything.
Fishing continued good for several days, and no vessel in sight. We were catching from 1200 to 1800 each day and running a fair size fish until we were obliged to get under way in order to heave overboard our gurry, cod heads and entrails, as our gurry kids were full, and to heave it where we lay would spoil our fishing, as the fish would be “gurry sick,” as fishermen call it. We played out our cable, put a large buoy on the end, and stood off to the south about two miles, threw it overboard, returned and picked up our moorings again, and commenced fishing again. Along in May fishing slacked up. I suppose the school had all been caught up. We lay here a week, averaging 500 to 600 daily.
One morning early two sails hove in sight, the first seen since we anchored, except some large ships to the north of us. Well, we were surprised to see that the schooners were from our own town, Orleans, one Captain Alvin Smith in the old schooner Lapwing, and Captain William Sherman in the schooner Stromboly. They were surprised to find that we had nearly half our catch, and felt pretty down in the mouth, for they had in all only 100 quintals, while we had about 400 quintals. The captain came on board and we exchanged news, and
[Pg 9]
 then anchored about half a mile either side of us. They met with no success, however, so only remained there a few days, when we all hove up and started for the Virgin Rock Ground, to the north east, about 100 miles from our old berth, and I think all the crew were glad to get away, for our hands were sore and badly swollen from handling salt and gurry.
When our distance was run up we hauled up jib and eased off fore sheet and hove lines over in about 40 fathoms of water. Lo and behold! no sooner was our lead overboard when we had fish on, fore and aft at the same time. The Captain jumped up and down like mad calling out to let go the anchor. Over she went, and it was only a few moments when sails were furled and the watch had their lines out with fairly good fishing. But we were on a small patch of ground, and every time the tide turned the vessel would swing round and strain, and in this position we could not get a bite, but when she swung round again the fishing was good again.
This was our second berth for three weeks, yet we were compelled to buoy the cable again as before and stand off to heave off our gurry. It was estimated we had about 650 quintals in our hold, our whole capacity being about 850 quintals.
About this time I began to get anxious, possibly it was home-sickness, but I kept asking the Captain, “When are we going to wet our salt?” That was the term we used to show that our salt was used up. To bother me he would say, “About the first of October,” but my good friend Mr. Sherman would tell me that July first would find us all cleaned up. In my spare time it was my duty to help him in the hold, where he was at work salting the fish. I used to bring the salt to him in a half bushel measure, and you may be sure that I spilled all of it that I could so the salt would be used up all the sooner and we could be on our way back home. I would ask him if he thought he was getting salt enough on the fish to keep them from turning red, and how he would laugh. I watched the salt bins and prayed that they would soon be emptied. Between cooking and fishing it was a busy time for me, and up to this time I had caught over 1200 head of fish, which meant some extra money for me, as I was to get 50 cents a hundred for all the fish that I caught. My position for fishing was aft over the stern, and up to this time good luck had been with me. At night, when we reported our daily catch, the Captain asked me if all my fish had eyes, but I did not understand what he meant until a loud roar of laughter from the men showed me that he meant to insinuate that I had been cheating in my count. At this I burst into tears, but again Mr. Sherman came to my rescue and soundly berated the Captain for continually picking on me.
After this my cooking was praised up by the Captain and he let me alone, as Mr. Sherman was a man whose words carried much weight. We had fish chowders for supper every night while on the Banks, and you may be sure that the fish was fresh, because scarce one half hour would pass before the fish would be in the pot. The previous winter at home my mother had taught me how to make bread and other things, but some of them I had forgotten, especially in regard to the boiling of rice. On this particular occasion I was ordered to prepare a supper of boiled rice and bean soup. I asked one of the crew about how much rice to use, and he told me to use at least two quarts, which he thought would be plenty, and you may be sure it was. I put it to soak in my big boiler
[Pg 10]
 on the stove, and as it commenced to cook it began to swell and soon ran over on top of the stove. I commenced to shift it into my other kettles, and soon had them all full and the water bucket besides. By this time the joke was known all over the boat, and when the Captain came down he said, “Cookie, are you sure you have saved out enough rice for yourself?” But I answered him right off, “Yes, sir; two buckets full,” at which they all had a hearty laugh, but you may be sure that they did not fool me again.
On July 21st, 1850, we had wet all of our salt, and the schooner was laden deep to her scuppers. On this glorious day we were to start for home, and on this day I was just nine years old, but the fact that we were to start for home was celebration enough for me. How many boys of this generation can say that they passed their ninth birthday in such a position? Thankful they should be that times have improved so that such work at so early an age is not often necessary.
We ran our flag to the mast-head, hauled down the trysail and bent on the main-sail and began to heave in the anchor cable. The Captain, with a big pair of mittens on, tends the cable as it comes in around the windlass, and the cook takes in the slack and coils it down around the fore-hatch, quite a job for an able-bodied man to attend to, but boys in those days often were able to do the work of a man. While heaving up the anchor our merry crew sang shanty songs, and when the anchor was up all sail was made and we were off for Cape Cod with a light east wind. The watch was set with two men in each watch of two hours each, and then I began to count the days it would take us to get home. A few days after I heard the Captain say we were in the latitude of Cape Cod, and thought sure we must soon be home, but learned afterwards that although in the latitude of the Cape we were a long ways off from it.
Our homeward journey was a pleasant one, and in about eight days we anchored inside of Billingsgate Island on a fine morning about eight o’clock. One could smell the land and the salt hay, and oh, how beautiful and green the land looked to me! We rowed up into the Town Creek, and each one started to walk to his home. All of my belongings were in a calico pillow case and I was bare-footed, but I ran nearly all the way home, some two miles distant, and never before nor since was I so glad to get back home. I was dirty as a pig, but fat and healthy, and mother laughed and cried over me as she welcomed me home. She brought out the big wash-tub and scrubbed me from head to foot, and when a clean suit was put on I hardly knew myself.
We made a stay of three days, and then took the schooner to Beverly, Mass., where we washed our fish out at a wharf owned by a Mr. Crowell, and prepared the fish for the flakes to have them properly dried.
We then made ready for the fish grounds in Cape Cod Bay to finish out the number of days required in order to get our bounty money which was offered by the State.
Then, when the tide was up, we went into Provincetown and fitted out for Fall mackerel fishing, or otherwise termed, hooking, and went down on the Maine coast, in and out of several harbors, and keeping with the fleet. We made a very successful season of our fall fishing, and the shoresmen cleared something over $700 to shore—a rich voyage for those days, while I, poor
[Pg 11]
 Cookie, labored and toiled from March 25th to the 23rd of May for the magnificent sum of $45, together with something like $15 for extra fish caught.
The Captain was a crafty old soul; he reported to my mother that I was the best boy and best cook he had ever had, but he failed to report to her what a “sassy” boy I was. However, I never liked him, and told mother that never again would I sail under him as cook.
Years have passed on and all my old shipmates who were with me on this, my first experience at sea, have answered the roll call. Our old craft met her fate years ago, and “Cookie” is the only survivor. Although I have passed the allotted “threescore years and ten,” I still look back on my first sea trip without regrets. The men of these days were true men, God-fearing and honest and upright in all of their dealings. As seamen they were unequalled or surpassed by none. The training-school of the Grand Banks fisherman was a rough and hard one, but most of the famous American sea captains were apprentices in that school that made it possible for the American Flag to be seen in every port of the commercial world and for the term “Yankee Skipper” to be used in a sense of praise and commendation.
The great Civil War, the introduction of steam and the unwise acts of a National Congress have caused American supremacy in the shipping lines to be destroyed, but it is to be hoped that the future may bring forth a solution of the problem that will once again put American ships under American skippers on old ocean’s bosom, and once again send our flag to the uttermost corners of the earth.


"""
#for length in [1000,2000,4000]:
#    cleaned_prompt = clean_text_to_prompt(input_text,length)
#    with open(f'txt_{length}.txt','x') as fp:
#        fp.write(cleaned_prompt)